name: Greeting
run-name: Greet ${{ inputs.subject }} ${{ inputs.greeting }} ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests against"
        type: choice
        options:
          - development
          - staging
          - production
        required: true
      subject:
        description: "Person to greet"
        type: string
        required: true
      greeting:
        description: "Choose a greeting"
        type: choice
        options:
          - Hello
          - Hi
          - Hey
          - Greetings
        required: true
        default: 'Hello'
      special_greeting:
        description: "Use special greeting?"
        type: boolean
        default: false

jobs:
  greeting_run:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Greet
        run: |
          if [ "${{ inputs.special_greeting }}" == "true" ]; then
            echo "Hey you are amazing, ${{ inputs.subject }}! Running in ${{ env.ENV }} environment"
          else
            echo "${{ inputs.greeting }}, ${{ inputs.subject }}! Running in ${{ env.ENV }} environment"
          fi
